name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          path: "src"
          fetch-depth: 1 # Descarga rápida para evitar Error 500

      - name: Checkout or Create Builds Branch
        uses: actions/checkout@v4
        continue-on-error: true # Por si la rama no existe aún
        with:
          ref: "builds"
          path: "builds"
          fetch-depth: 1

      - name: Clean or Create builds folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/builds
          rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: |
          cd $GITHUB_WORKSPACE/src
          echo "WASMAPI=${{ secrets.WASMAPI_KEY }}" > local.properties

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make --stacktrace
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds/ || echo "No cs3 found"

      - name: Restore My Custom JSON
        run: |
          if [ -f "$GITHUB_WORKSPACE/src/plugins.json" ]; then
            cp -f "$GITHUB_WORKSPACE/src/plugins.json" "$GITHUB_WORKSPACE/builds/plugins.json"
            echo "¡Éxito! Tu plugins.json personalizado ha sido restaurado."
          else
            echo "ERROR: No se encontró 'src/plugins.json'."
            exit 1
          fi

      - name: Commit and Push builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/builds
          git init
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # ELIMINA EL ORIGIN SI YA EXISTE PARA EVITAR EL ERROR
          git remote remove origin || true
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          
          git checkout -b builds || git checkout builds
          git add .
          
          if git diff --staged --quiet; then
            echo "Nada que actualizar."
          else
            git commit -m "Build: Actualización automática de plugins y JSON"
            git push origin builds --force
          fi